#!/usr/bin/env bash

export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
export QT_QPA_PLATFORMTHEME="qt5ct"
autorandr -c

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s "$SCRIPTPATH"/down /tmp/leftwm-theme-down

# Boot picom (composer)
if [ -x "$(command -v picom)" ]; then
  picom --experimental-backends --config "$SCRIPTPATH"/picom/picom.conf &> /dev/null &
fi

# Set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

# Set background wallpaper
if [ -x "$(command -v feh)" ]; then
  feh --no-fehbg --bg-fill /usr/share/backgrounds/archlinux/simple.png # wallpapers should be installed
fi

#################################
# Applications to run at startup
#################################

# Notifications
dunst -conf "$SCRIPTPATH"/dunst/dunstrc &
# Start Polybar easy way
polybar -c "$SCRIPTPATH"/polybar/polybar.config &> /dev/null &
# Facny resources monitoring
conky --config "$SCRIPTPATH"/conky/conky.conf &> /dev/null &
